Repository ovh-ux/ovh-ui-kit-documentation, pull requests merged in 2018-06, with the labels that each got.

#94 feat(oui-collapsible): collapsible component addition
  src/ovh-ui-angular/ovh-ui-angular.config.json
  src/ovh-ui-kit/ovh-ui-kit.config.json
Labels: cui migration, feature, ok for merge, quality check ok

#106 feat: oui skeleton
  src/ovh-ui-angular/ovh-ui-angular.config.json
  src/ovh-ui-kit/ovh-ui-kit.config.json
Labels: cui migration, feature, ok for merge, quality check ok

#95 feat: oui clipboard
  src/ovh-ui-angular/ovh-ui-angular.config.json
  src/ovh-ui-kit/ovh-ui-kit.config.json
Labels: cui migration, feature, quality check

#104 (oui-slideshow): add new slideshow component
  src/ovh-ui-angular/ovh-ui-angular.config.json
Labels: feature, quality check ok

#117 feat(oui-doc): add margin on previews
  build/loaders/markdown-renderer.js
  src/index.less
Labels: enhancement

#119 feat(page-header): add page-header component
  src/ovh-ui-angular/ovh-ui-angular.config.json
  src/ovh-ui-kit/ovh-ui-kit.config.json
Labels: feature, quality check ok

#118 feat(oui-tile): group
  src/ovh-ui-angular/ovh-ui-angular.config.json
  src/ovh-ui-kit/ovh-ui-kit.config.json
Labels: feature, quality check ok

#121 feat(header-tabs): add header-tabs component
  src/ovh-ui-angular/ovh-ui-angular.config.json
  src/ovh-ui-kit/ovh-ui-kit.config.json
Labels: feature, quality check ok

#123 chore(*): change ui-kit version to 2.16
  package.json
  yarn.lock
Labels: enhancement
