Repository ovh-ux/ovh-ui-kit-documentation, pull requests merged in 2018-05, with the labels that each got.

#103 docs: help on components reorganization
  README.md
Labels: enhancement, ok for merge

#99 chore: update ui-router
  package.json
  src/index.js
  yarn.lock
Labels: enhancement, ok for merge

#105 hotfix(markdown-renderer): fix code preview toggle feature
  build/loaders/markdown-renderer.js
Labels: bug

#113 chore: bump version of dependencies
  package.json
  yarn.lock
Labels: enhancement

#114 Datagrid: refresh
  src/ovh-ui-angular/controllers/datagrid.controller.js
Labels: feature, quality check ok
